version: '3'
services:
  web:
    container_name: real_estate
    build: .
    ports:
      - 5000:5000
    volumes: 
      - .:/app
    depends_on: 
      - db
    restart: always
  db:
    image: mysql:5.7
    # build: .
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123
      # MYSQL_USER: root
      # MYSQL_PASSWORD: 123
      MYSQL_DATABASE: real_estate_db
    volumes:
      - ./mydb:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      MYSQL_ROOT_PASSWORD: 123
    links:
      - db